/* Write your PL/SQL query statement below */
    SELECT MGR.EMPLOYEE_ID
         , MGR.NAME
         , COUNT(EMP.EMPLOYEE_ID) AS REPORTS_COUNT
         , ROUND(AVG(EMP.AGE)) AS AVERAGE_AGE
      FROM EMPLOYEES EMP
      JOIN EMPLOYEES MGR
        ON EMP.REPORTS_TO   = MGR.EMPLOYEE_ID
  GROUP BY MGR.EMPLOYEE_ID
         , MGR.NAME
  ORDER BY MGR.EMPLOYEE_ID;